[project]
name = "piper-arm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "lerobot>=0.4.0",
  "piper-sdk>=0.6.1",
  "pyrealsense2>=2.56.5.9235",
  "opencv-contrib-python>=4.12.0.88",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
