job_name: smolvla-libero-16-chunk
num_workers: 8
batch_size: 64
steps: 100_000
eval_freq: 10_000

dataset:
  repo_id: reece-omahoney/libero

env:
  type: libero
  task: libero_10
  fps: 10

# these are overriden when finetuning
policy:
  type: smolvla
  repo_id: reece-omahoney/smolvla-libero-16-chunk
  device: cuda
  chunk_size: 16
  n_action_steps: 8
  load_vlm_weights: true
  resize_imgs_with_padding: [256, 256]
  max_state_dim: 8
  max_action_dim: 7

eval:
  n_episodes: 1
  batch_size: 1

wandb:
  enable: true
  disable_artifact: true
